name: ed_sales
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  dropdown_search: ^6.0.3
  image_picker: ^1.1.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  pointycastle: ^4.0.0
  http: ^1.5.0
  syncfusion_flutter_pdfviewer: ^31.2.2
  share_plus: ^12.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

# 🟡 Hii sehemu lazima iwe hapa nje ya dev_dependencies
flutter_icons:
  android: true
  ios: true
  image_path: "assets/pos.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
